spring:
  application:
    name: identity-service
  datasource:
    url: "jdbc:postgresql://localhost:5435/identity_service"
    username: "postgres"
    password: "test"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8091

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
