global:
  resolve_timeout: 5m
  smtp_smarthost: "papercut-smtp:25" # Canlı bir sistemde bu değiştirilecek
  smtp_from: "alertmanager@example.com"
  smtp_auth_username: "alertmanager"
  smtp_auth_password: "alertmanager"

route:
  receiver: "email-alert"

receivers:
  - name: "email-alert"
    email_configs:
      - to: "test@example.com"
        from: "alertmanager@example.com"
        require_tls: false
