global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "config-server-app"
    scrape_interval: 30s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["config-server:8079"]

#  - job_name: "self"
#    scrape_interval: 30s
#    static_configs:
#      - targets: ["localhost:9090"]
