spring:
  application:
    name: "config-server"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/halitkalayci/turkcell-microservice-configs.git"
          default-label: master
server:
  port: 8079

management:
  endpoints:
    web:
      exposure:
        include: "*"
  enpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"


